Zircon Hobbies/Models/Gunpla.cs
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Zircon_Hobbies.Models
{
    public class Gunpla
    {

    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required")]
    [StringLength(100, ErrorMessage = "Name cannot be longer than 100 characters.")]
    public string Name { get; set; }

    [Required(ErrorMessage = "Type is required")]
    public string Type { get; set; }

    [Required(ErrorMessage = "Scale is required")]
    public string Scale { get; set; }

    [Required(ErrorMessage = "Production Company is required")]
    public int ProductionCompanyId { get; set; }

    public Production_Company ProductionCompany { get; set; }
 
    [Required(ErrorMessage = "Price is required")]
    [Range(1, 10000, ErrorMessage = "Price must be between 1 and 10,000.")]
    public double Price { get; set; }


    }
}

Zircon Hobbies/Models/GunplaViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security;

namespace Zircon_Hobbies.Models
{
    public class GunplaViewModel
    {

        public List<Gunpla>? Gunplas { get; set; }
        public SelectList? Types { get; set; }
        public SelectList? Scale { get; set; }
        public string? GunplaType { get; set; }
        public string? GunplaScale { get; set; }
        public string? SearchString { get; set; }

        public IEnumerable<SelectListItem> ProductionCompany { get; set; }

    }
}

Zircon Hobbies/Controllers/GunplasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.View;
using Zircon_Hobbies.Data;
using Zircon_Hobbies.Models;
using PagedList;

namespace Zircon_Hobbies.Controllers
{
    public class GunplasController : Controller
    {
        private readonly Zircon_HobbiesContext _context;

        public GunplasController(Zircon_HobbiesContext context)
        {
            _context = context;
        }


        [Authorize]
        public async Task<IActionResult> Index(string GunplaType, string GunplaScale, string searchString)
        {

            if (_context.Gunpla == null)
            {
                return Problem("Enttiy set 'Zircon_HobbiesContext.Gunpla' is null");
            }

            IQueryable<string> TypeQuery = from g in _context.Gunpla
                                           orderby g.Type
                                           select g.Type;

            IQueryable<string> ScaleQuery = from s in _context.Gunpla
                                            orderby s.Scale
                                            select s.Scale;

            var gunplas = _context.Gunpla
         .Include(g => g.ProductionCompany)
         .AsQueryable();



            if (!string.IsNullOrEmpty(searchString))
            {
                gunplas = gunplas.Where(z => z.Name!.ToUpper().Contains(searchString.ToUpper()));
            }

            if (!string.IsNullOrEmpty(GunplaScale))
            {
                gunplas = gunplas.Where(c => c.Scale == GunplaScale);
            }

            if (!string.IsNullOrEmpty(GunplaType))
            {
                gunplas = gunplas.Where(x => x.Type == GunplaType);
            }

            var GunplaVM = new GunplaViewModel
            {
                Types = new SelectList(await TypeQuery.Distinct().ToListAsync()),
                Scale = new SelectList(await ScaleQuery.Distinct().ToListAsync()),
                Gunplas = await gunplas.ToListAsync()
            };

            return View(GunplaVM);

        }

        // GET: Gunplas/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gunpla = await _context.Gunpla
                .Include(g => g.ProductionCompany)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gunpla == null)
            {
                return NotFound();
            }

            return View(gunpla);
        }

        // GET: Gunplas/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {

            ViewBag.ProductionCompany = _context.Production_Company
            .Select(pc => new SelectListItem
            {
                Value = pc.Id.ToString(),
                Text = pc.Name
            }).ToList();

            return View();
        }

        // POST: Gunplas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Type,Scale,ProductionCompanyId,Price")] Gunpla gunpla)
        {

            ModelState.Remove("ProductionCompany");

            if (ModelState.IsValid)
            {
                _context.Add(gunpla);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(gunpla);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gunpla = await _context.Gunpla.FindAsync(id);
            if (gunpla == null)
            {
                return NotFound();
            }

            ViewBag.ProductionCompany = _context.Production_Company
        .Select(pc => new SelectListItem
        {
            Value = pc.Id.ToString(),
            Text = pc.Name
        }).ToList();

            return View(gunpla);
        }

        // POST: Gunplas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Type,Scale,ProductionCompanyId,Price")] Gunpla gunpla)
        {
            if (id != gunpla.Id)
            {
                return NotFound();
            }

            ModelState.Remove("ProductionCompany");

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gunpla);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GunplaExists(gunpla.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.ProductionCompany = _context.Production_Company
        .Select(pc => new SelectListItem
        {
            Value = pc.Id.ToString(),
            Text = pc.Name
        }).ToList();

            return View(gunpla);
        }

        // GET: Gunplas/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gunpla = await _context.Gunpla
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gunpla == null)
            {
                return NotFound();
            }

            return View(gunpla);
        }

        // POST: Gunplas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gunpla = await _context.Gunpla.FindAsync(id);
            if (gunpla != null)
            {
                _context.Gunpla.Remove(gunpla);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GunplaExists(int id)
        {
            return _context.Gunpla.Any(e => e.Id == id);
        }
    }
}

Zircon Hobbies/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using Zircon_Hobbies.Data;
using Zircon_Hobbies.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Zircon_Hobbies.Controllers
{
    public class ShoppingCartController : Controller
    {

        private readonly Zircon_HobbiesContext _context;
        private readonly List<cartItem> _cartItems;

        public ShoppingCartController(Zircon_HobbiesContext context)
        {
            _context = context;
            _cartItems = new List<cartItem>();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddToCart(int id) 
        {
            
            var GunplaToAdd = _context.Gunpla.Find(id);

            var cartItems = HttpContext.Session.Get<List<cartItem>>("Cart") ?? new List<cartItem>();

            var existingCartItem = cartItems.FirstOrDefault(item => item.Gunpla.Id == id);

            if (existingCartItem != null)
            {
                existingCartItem.Quantity++;
            }
            else
            {
                cartItems.Add(new cartItem
                {
                    Gunpla = GunplaToAdd,
                    Quantity = 1
                });
            }

            HttpContext.Session.Set("Cart", cartItems);

            TempData["CartMessage"] = $"{GunplaToAdd.Name} added to cart"; 

            return RedirectToAction("ViewCart");

        }

        [Authorize]
        public IActionResult ViewCart()
        {

            var cartItems = HttpContext.Session.Get<List<cartItem>>("Cart") ?? new List<cartItem>();

            foreach (var item in cartItems)
            {
                item.Gunpla = _context.Gunpla
                    .Include(g => g.ProductionCompany)
                    .FirstOrDefault(g => g.Id == item.Gunpla.Id);
            }

            var cartViewModel = new ShoppingCartView
            {
                cartItems = cartItems,
                TotalPrice = cartItems.Sum(item => item.Gunpla.Price * item.Quantity)
            };

            ViewBag.CartMessage = TempData["CartMessage"];

            return View(cartViewModel);
        }

        public IActionResult RemoveItem(int id)
        {
            var cartItems = HttpContext.Session.Get<List<cartItem>>("Cart") ?? new List<cartItem>();

            var itemToRemove = cartItems.FirstOrDefault(item => item.Gunpla.Id == id);

            TempData["CartMessage"] = $"{itemToRemove.Gunpla.Name} removed from cart";

            if (itemToRemove.Quantity > 1)
            {
                itemToRemove.Quantity--;
            }
            else
            {
                
                cartItems.Remove(itemToRemove);
            }

            HttpContext.Session.Set("Cart", cartItems);

            return RedirectToAction("ViewCart");
        }

        public IActionResult Checkout()
        {
            var cartItems = HttpContext.Session.Get<List<cartItem>>("Cart") ?? new List<cartItem>();

            if (cartItems.Count == 0)
            {
                TempData["CartMessage"] = $"Purchase Unsuccesful";
            } else
            {
                TempData["CartMessage"] = $"Purchase Succesful";
            }

            foreach (var item in cartItems)
            {
                _context.Purchases.Add(new Purchase
                {
                    GunplaId = item.Gunpla.Id,
                    Quantity = item.Quantity,
                    PurchaseDate = DateTime.Now,
                    Total = item.Gunpla.Price * item.Quantity
                });

              

            }

            _context.SaveChanges();

            ViewBag.CartMessage = TempData["CartMessage"];

            HttpContext.Session.Set("Cart", new List<cartItem>());

            return RedirectToAction("Index", "Home");

        }
    }
}

Zircon Hobbies/Views/Gunplas/Create.cshtml
@model Zircon_Hobbies.Models.Gunpla

@{
    ViewData["Title"] = "Create";
}

<h1>Add a new Gunpla</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Scale" class="control-label"></label>
                <input asp-for="Scale" class="form-control" />
                <span asp-validation-for="Scale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductionCompanyId" class="control-label"></label>
                <select asp-for="ProductionCompanyId" class="form-control" asp-items="ViewBag.ProductionCompany">
                    <option value="">Select a Production Company</option>
                </select>
                <span asp-validation-for="ProductionCompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Zircon Hobbies/Views/Gunplas/Delete.cshtml
@model Zircon_Hobbies.Models.Gunpla

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gunpla</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Scale)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Scale)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductionCompanyId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductionCompanyId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Zircon Hobbies/Views/Gunplas/Details.cshtml
@model Zircon_Hobbies.Models.Gunpla

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<br />
<input type="hidden" value="@Model.Id"/>

<div>
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Scale)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Scale)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductionCompany.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductionCompany.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt class="list-group-item"><a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@Model.Id" cite="btn btn-primary">Add to Cart</a></dt>

    </dl>
</div>
<div>
    @if(User.IsInRole("Admin")){
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    }
    <br />
    <a asp-action="Index">Back to List</a>
</div>

Zircon Hobbies/Views/Gunplas/Edit.cshtml
@model Zircon_Hobbies.Models.Gunpla

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Gunpla</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Scale" class="control-label"></label>
                <input asp-for="Scale" class="form-control" />
                <span asp-validation-for="Scale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductionCompanyId" class="control-label"></label>
                <select asp-for="ProductionCompanyId" class="form-control" asp-items="ViewBag.ProductionCompany">
                    <option value="">Select a Production Company</option>
                </select>
                <span asp-validation-for="ProductionCompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Zircon Hobbies/Views/Gunplas/Index.cshtml
@model Zircon_Hobbies.Models.GunplaViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Gundam Models</h1>

<form asp-controller="Gunplas" asp-action="Index" method="get">

    <p>
        <select asp-for="GunplaType" asp-items="Model.Types">
            <option value="">All</option>
        </select>

        <select asp-for="GunplaScale" asp-items="Model.Scale">
            <option value="">All</option>
        </select>

        <label>Name: <input type="text" onfocus="this.value=''" asp-for="SearchString"></label>
        <input type="submit" value="Filter"/>

    </p>    
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Gunplas![0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gunplas![0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Scale)
            </th>
            <th>
               Brand
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gunplas![0].Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Gunplas) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Scale)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.ProductionCompany.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <text> | </text>
                    }
                    
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                    @if (User.IsInRole("Admin"))
                    {
                        <text> | </text>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>

<p>
    @if (User.IsInRole("Admin"))
    {
        <a asp-action="Create">Create New</a>
    }
</p>